inventory_bundle:
    resource: "@AppBundle/Controller"
    type: annotation
    prefix: /inventory

inventory_api:
    resource:     "@AppBundle/Controller/Api/Rest"
    type:         rest
    prefix:       api
    requirements:
        _format:  json
    defaults:
        version:  latest